require("dotenv").config()

const db = require ("./config/database")

const Product = require("./models/Product")

Product.create (
    {
    brand: "Olga Mesh" ,
    type: "reloj",
    model: "Tommy Hilfigher",
    description: "Un reloj atemporal para toda ocasión. Si no querés estar pensando con qué combinarlo o si estás buscando regalar un reloj, entonces Olga Mesh es la elección ideal. Su tonalidad negra mate con destellos ‘rose gold’ la convierten en una pieza dificil de igualar. Tiene todo lo que necesitás.",
    price: 79,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/olga-mesh-abaco.jpg?fit=120%2C120&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/olga-mesh-abaco-4.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/olga-mesh-2.jpg?fit=1080%2C1080&ssl=1"],  
    },
    {
        brand: "Porter Sepia" ,
        type: "reloj",
        model: "Abaco",
        description: "Un reloj único, diferente y con mucha personalidad. Si querés el Porter Sepia, primero te la tenés que creer un poco.",
        price: 35,
        likes: [],
        stock: 50,
        photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2020/12/Porter-Sepia.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/12/porter-sepia-1.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/12/portersepia-2-2.jpg?fit=1500%2C1500&ssl=1"],
},
{   
    brand: "Enrico Toffee" ,
    type: "reloj",
    model: "Abaco",
    description: "No vas a conocer un reloj tan clásico y minimalista como el Enrico Toffee.",
    price: 45,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2020/10/enrico-toffee-2.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/enrico-toffee-abaco-4.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/10/enrico-toffee-abaco.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Darwin Sepia" ,
    type: "reloj",
    model: "Abaco",
    description: "A la hora de usar un Reloj Clásico, el Darwin Sepia es el indicado para toda ocasión. Llamá la atención de todo el mundo con su combinación tonos plateados y negros y dale más identidad con nuestra correa de cuero marrón ‘tostado’",
    price: 45,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/darwin-1.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/darwin-sepia.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/02/darwin-sepia-2.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Billetera Bifold Camel con Cierre" ,
    type: "billetera",
    model: "Abaco",
    description: "Card Slider Fabricado de aleación de aluminio y titanio recubierto en Cuero Genuino.Tus tarjetas más importantes ahora están protegidas contra cualquier flexión y contra lectores RFID (Radio Frecuency Identification) no deseados, lo que evitará que la información de tus tarjetas sea copiada.",
    price: 20,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_black_2.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_black_2_abaco.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_black_3.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Mochila WRK Preto" ,
    type: "mochilas",
    model: "Abaco",
    description: "Impronta moderna con el toque justo de lo clásico.Te va a quedar bien hoy, y también dentro de 20 años.",
    price: 59,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2021/04/mochila-wrk-abaco-detalle-1.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2021/04/mochila-cuero-hombre-3.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2021/04/mochila-wrk-abaco.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Mochila Citric M" ,
    type: "mochilas",
    model: "Abaco",
    description: "Una mochila para la facultad, para ir a trabajar, o para irte de viaje. Espaciosa, liviana, y resistente para acompañarte donde la necesites.",
    price: 85,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2022/08/mochila-m-safari-side.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/08/mochila-m-safari-back.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/08/mochila-m-lemon-side.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Mochila XS Trash" ,
    type: "mochilas",
    model: "Abaco",
    description: "El tamaño ideal para salir a la calle con lo esencial… y un poco más también.",
    price: 65,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2021/04/mochila-xs-trash-abaco.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2021/04/mochila-xs-abaco-back-1.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Tarjetero Camel" ,
    type: "billetera",
    model: "Abaco",
    description: "Creada con cuero vacuno, nuestro Tarjetero Camel cuenta con seis bolsillos para tarjetas y un compartimento interno para billetes.",
    price: 15,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2020/03/tarjetero-camel-abaco.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/03/bifold-cierre-preto-iso-1.jpg?fit=1500%2C1500&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2020/03/tarjetero-1.jpg?fit=1500%2C1500&ssl=1"],

},
{   
    brand: "Magnet" ,
    type: "billetera",
    model: "Abaco",
    description: "Card Slider Fabricado de aleación de aluminio y titanio recubierto en Cuero Genuino.Tus tarjetas más importantes ahora están protegidas contra cualquier flexión y contra lectores RFID (Radio Frecuency Identification) no deseados, lo que evitará que la información de tus tarjetas sea copiada.",
    price: 85,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_black_01.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_duo.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/09/magnet_black_3.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Bolso WKD Cordura" ,
    type: "bolsos",
    model: "Abaco",
    description: "A donde sea que viajes, nunca vayas sin tu Bolso WKD. Diseñado para viajar ligero sin pensar en el espacio. Ideal para escapadas de fin de semana ó para entrenar.",
    price: 85,
    likes: [],
    stock: 50,
    photo: ["https://i0.wp.com/abaco.la/wp-content/uploads/2022/07/bolso-wkd-sq-4.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/07/bolso-wkd-sq-4.jpg?fit=1080%2C1080&ssl=1", "https://i0.wp.com/abaco.la/wp-content/uploads/2022/03/bolso-black-2.jpg?fit=1080%2C1080&ssl=1"],

},
{   
    brand: "Bolso De Mano Doble Cierre" ,
    type: "bolsos",
    model: "Bando",
    description: "Bolso de mano, comodo, ligero con un estilo rustico",
    price: 30,
    likes: [],
    stock: 50,
    photo: ["https://www.bandobasicos.com.ar/3641-thickbox_default/bolso-de-mano-doble-cierre-neto-negro.jpg"],
},
{   
    brand: "Anteojos Jerome" ,
    type: "anteojos",
    model: "elburgues",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas",
    price: 125,
    likes: [],
    stock: 50,
    photo: ["https://cdn.elburgues.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/0/l0017jeria.jpg"],
},
{   
    brand: "ANTEOJO IZIPIZI #D GREN" ,
    type: "anteojos",
    model: "elburgues",
    description: "Gafas de sol para deportes acuáticos y conducción. Cristales polarizados 100 % UV categoría 3. Modelo mixto y universal. Sin graduar. Estuche incluido en la caja.",
    price: 95,
    likes: [],
    stock: 50,
    photo: ["https://cdn.elburgues.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/-/c-sun-green-gafas-sol.jpg"],
},
{   
    brand: "ANTEOJOS JEROME BLACK" ,
    type: "anteojos",
    model: "elburgues",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 115,
    likes: [],
    stock: 50,
    photo: ["https://cdn.elburgues.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/0/l0017jeri6.jpg"],
},
{   
    brand: "ANTEOJOS DOMINIQUE" ,
    type: "anteojos",
    model: "elburgues",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 115,
    likes: [],
    stock: 50,
    photo: ["https://cdn.elburgues.com/media/catalog/product/cache/1/small_image/456x556/9df78eab33525d08d6e5fb8d27136e95/l/0/l0017domi7.jpg"],
},
{   
    brand: "AQUE DE LOEWE EDT" ,
    type: "perfume",
    model: "juleriaque",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 115,
    likes: [],
    stock: 50,
    photo: ["https://juleriaque.vteximg.com.br/arquivos/ids/170559-1000-1000/agua-de-loewe-edt-245438DF10AA3D11D5D348D328BDD6D7.jpg?v=637455397859130000"],
},
{   
    brand: "CK BE EDT" ,
    type: "perfume",
    model: "juleriaque",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 115,
    likes: [],
    stock: 50,
    photo: ["https://juleriaque.vteximg.com.br/arquivos/ids/156358-1000-1000/ck-be-edt-B02551977EC9D9F8F5AEE3A726D06DA4.jpg?v=637336334865970000"],
},
{   
    brand: "CK EVERYONE EDT" ,
    type: "perfume",
    model: "juleriaque",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 115,
    likes: [],
    stock: 50,
    photo: ["https://juleriaque.vteximg.com.br/arquivos/ids/167647-150-150/ck-everyone-edt-4822F957E50D072C2348914B5BA9114D.jpg?v=637363932176430000"],
},
{   
    brand: "FLEUR DE PORTOFINO EDP" ,
    type: "perfume",
    model: "juleriaque",
    description: "Las gafas cumplen con las normas internacionales de calidad, bajo conformidad con las disposiciones y requisitos fundamentales de seguridad establecidos en las normas europeas, americanas y australianas.",
    price: 505,
    likes: [],
    stock: 50,
    photo: ["https://juleriaque.vteximg.com.br/arquivos/ids/165202-150-150/fleur-de-portofino-edp-C543F2DB6D475EE341310BF4D9A62C8E.jpg?v=637347506141800000"],
},
)